### ISSUE TITLE
Add support for clean teardown + reconstruction

### ISSUE THREAD

**Issue by Nopik** [arobson/rabbot#35]
Currently it seems that Rabbot is not able to reconnect succesfully, once it reaches retry limit. Whatever I'm trying to do (like calling .configure() again, calling .addConnection(), .addConnection() with new name, calling .retry(), .closeAll()+ all of the above, .shutdown() + all of the above, and so on), it just can't reconnect cleanly. At best, I'm getting this (e.g. by calling `rabbot.shutdown(); rabbot.configure( originalConfiguration )`:

```
Potentially unhandled rejection [8] TypeError: Cannot read property 'define' of undefined
    at machina.Fsm.extend._define (.../app/node_modules/rabbot/src/exchangeFsm.js:43:17)
    at .<anonymous> (.../app/node_modules/rabbot/src/exchangeFsm.js:58:10)
    at Object.invokeSubscriber (.../app/node_modules/monologue.js/lib/monologue.js:181:19)
    at invoker (.../app/node_modules/monologue.js/lib/monologue.js:430:11)
    at arrayEach (.../app/node_modules/monologue.js/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (.../app/node_modules/monologue.js/node_modules/lodash/index.js:3345:13)
    at Monologue.emit (.../app/node_modules/monologue.js/lib/monologue.js:439:6)
    at machina.Fsm.extend.states.acquired._onEnter (.../app/node_modules/rabbot/src/amqp/iomonad.js:196:11)
    at _.extend.transition (.../app/node_modules/machina/lib/machina.js:433:27)
    at Fsm.(anonymous function) [as transition] (.../app/node_modules/machina/lib/machina.js:580:60)
    at machina.Fsm.extend._onAcquisition (.../app/node_modules/rabbot/src/amqp/iomonad.js:108:9)
    at tryCatchReject (.../app/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (.../app/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (.../app/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (.../app/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (.../app/node_modules/when/lib/Scheduler.js:62:19)
Potentially unhandled rejection [9] TypeError: Cannot read property 'define' of undefined
    at machina.Fsm.extend._define (.../app/node_modules/rabbot/src/exchangeFsm.js:43:17)
    at .<anonymous> (.../app/node_modules/rabbot/src/exchangeFsm.js:58:10)
    at Object.invokeSubscriber (.../app/node_modules/monologue.js/lib/monologue.js:181:19)
    at invoker (.../app/node_modules/monologue.js/lib/monologue.js:430:11)
    at arrayEach (.../app/node_modules/monologue.js/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (.../app/node_modules/monologue.js/node_modules/lodash/index.js:3345:13)
    at Monologue.emit (.../app/node_modules/monologue.js/lib/monologue.js:439:6)
    at machina.Fsm.extend.states.acquired._onEnter (.../app/node_modules/rabbot/src/amqp/iomonad.js:196:11)
    at _.extend.transition (.../app/node_modules/machina/lib/machina.js:433:27)
    at Fsm.(anonymous function) [as transition] (.../app/node_modules/machina/lib/machina.js:580:60)
    at machina.Fsm.extend._onAcquisition (.../app/node_modules/rabbot/src/amqp/iomonad.js:108:9)
    at tryCatchReject (.../app/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (.../app/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (.../app/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (.../app/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (.../app/node_modules/when/lib/Scheduler.js:62:19)
```

after which Rabbot claims that he has connection (`connected` is sent), but apparently is has no exchange configured, thus all publish calls fail.

I do not prefer to kill my whole process upon such failure. Rabbit is only small part of the whole, and it causing to shutdown whole world is little too inconvenient for me. Sure, alerting/monitoring should fire an alert to admin. Yes, all pending promises for publish should be rejected and not retried. Yes, I can create new connection from scratch. Yes, it will not fix the network. Restarting everything wont fix it, either, though. What I'd prefer to have is to have always-on, self-healing connection, based on best effort. I.e. if in given minute it cant deliver, fine, reject the promise. And it seems, that Rabbot has everything else I need. And I guess that this clean reconnect is like 99% there, too ;)

**Comment by arobson** [comment]
@Nopik - I _think_ this was related to issues I just closed and fixed with 1.0.6. Please pull the latest and give this a try. You shouldn't have to call `configure` or `addConnection`. If you really want your service to stay up indefinitely, listen for the `unreachable` event and call `rabbot.retry()`. The errors you are getting I was able to reproduce when fixing issue #38. And when I resolved those, I was able to kill the broker entirely in test services for minutes at a time, then bring it back up again and have services resume messaging.

**Comment by Nopik** [comment]
Well, it is still not fixed with 1.0.6, I'm afraid. A couple of things:

1) when I restart rmq then rabbot does reconnect, claim to rebuild topology, but it doesnt create exchange (I see no logs about creating exchange), and then publish attempt fail due to exchange not existing on default connection. Needlessly to say, that exchange do exist before disconnect. I tried  exchange in question defined as `persistent: true` as well as `false` in the config. The exchange is defined in RMQ (at least when is set to persistent). Worker seem to work fine after reconnect - if I publish message from RMQ web management UI, worker is picking it up.

2) When such thing happens, node process doesnt shut down clearly. I have set up .close()/.shutdown()/.exit() etc. on anything on my process + sigint handler, so when things are right ctrl-c causes my node process to exit cleanly immediately (shutting down express, database, redis connections, rmq connections, etc.) After rmq reconnect I see that rabbot is keeping some old connection and doesnt shut down correctly anymore (but it does if I call shutdown() before rmq disconnect)

3) When I stop rmq, start my node process, let rabbot fail, then start rmq, it doesnt fully connect, either. But, it is failing because no endpoints could be reached, arguably. It doesnt cleanly shuts down in that case, too.

**Comment by Nopik** [comment]
Things started to work much better, when I added `configureExchanges` call in `Topology.prototype.onReconnect`
```
      return this.configureExchanges( this.definitions.exchanges, true )
        .then( function() {
             return this.configureBindings( this.definitions.bindings, true )
             ....
        }.bind( this ) );
```
and modified `createExchange`:

```
Topology.prototype.createExchange = function( options ) {
  this.definitions.exchanges[ options.name ] = options;
	return this.createPrimitive( Exchange, "exchange", options );
};
```

With those 2 small changes, when reconnection is done, both publisher and workers are working fine.

HOWEVER, shutting down is still not working fine, some old connection must be kept somewhere.

**Comment by Nopik** [comment]
The connection leak (i.e. unable to shutdown cleanly) happens only when unreachable is sent. If I set big retry and I restart RMQ quickly, then even if some publish() calls are made while RMQ is offline, then after reconnection rabbot is able to restore operations and shutdown cleanly. Once unrechable/retry is called, things are still working, but shutdown is not clean.

**Comment by arobson** [comment]
@nopik - can you send me an example of your configuration or setup? I would also like to know what version of RabbitMQ you're running.

The scenario you are describing is not one I have seen or reproduced. Being able to see how you're setting things up will help me understand the scenario better and maybe help me figure out what edge case is causing this behavior.

**Comment by Nopik** [comment]
Yeah, I was sure that you'll ask ;) Fortunately it is easy for me to provide standalone example. I have it in ES6 code, hopefully that wont be a problem for you.

```
import rabbit from 'rabbot';

let config = {
	connection: {
		user: "guest",
		pass: "guest",
		server: "192.168.99.100",
		port: 5672,
		vhost: "%2f",
		timeout: 3000,
		retryLimit: 3, // change this to 30 and try to quickly restart RMQ -> problem doesnt happen
		failAfter: 1000000,
		replyQueue: false
	},
	exchanges: [
		{ name: "usermgmt", type: "topic", persistent: true }
	],
	queues: [
		{ name: "emails", subscribe: true, noBatch: true }
	],
	bindings: [
		{ exchange: "usermgmt", target: "emails", keys: [ "email.#" ] }
	],
	logging: {
		adapters: {
			stdOut: {
				level: 4,
				bailIfDebug: true
			}
		}
	}
};

// rabbit.rejectUnhandled();

rabbit.handle( { type: 'email.test' }, ( msg )=> {
	console.log( `test worker`, msg.body.cnt );
	msg.ack();
} );

let cnt = 1;
let i = setInterval( ()=> {
	console.log( `publish`, cnt );
	rabbit.publish( 'usermgmt', { routingKey: 'email.test', body: { cnt } } )
		.catch( ( err )=> {
			console.log( `Unable to publish to ${routingKey}:`, err );
		} );

	cnt++;
}, 5000 );

rabbit.on( 'unreachable', ()=> {
	console.log( "Rabbot is giving up." );
	rabbit.retry();
} );

rabbit.configure( config ).then( ()=> {
	console.log( "Rabbot connected." );
}, ( err )=> {
	console.log( "Rabbot cannot connect:", err );
} );

let exit_handler = function( name ) {
	return function() {
		console.log( "Shutting down" );
		rabbit.shutdown();
		clearInterval( i );
	};
};

process.on( 'SIGINT', exit_handler( 'SIGINT' ) );
```

If you configure RMQ connection to your server, and run this code, you'll see that it connects and every 5 seconds it does send+receive message. If you ctrl-c it, it shuts down gracefully and exit to shell. If, however, there were RMQ restart in between, all hell breaks loose. With my modifications I mentioned earlier, things are much better - connectivity restores fully, but ctrl-c stops working. Also, if RMQ restart before `unreachable` is sent, things are OK, too.

I'm using `rabbitmq:3-management` tag on RMQ Docker Hub image, which now reports to me: RabbitMQ 3.6.5, Erlang 19.0.

I'm also having that `rejectUnhandled()` enabled in my production code, though that doesnt seem to affect the behavior which we discuss.

**Comment by Nopik** [comment]
Also, Node v6.3.1, if that matters.

**Comment by Nopik** [comment]
@arobson did you had a chance to take a look on this? Can I help somehow?

**Comment by arobson** [comment]
@Nopik I'll try to get to this soon - I've not had a chance this week but hopefully I'll get to it tomorrow evening.

**Comment by johnraber** [comment]
@Nopik  I'm running your suggested fixes to topology.js in my own branch and it works when calling```
 rabbit.on( 'unreachable', ()=> {
    console.log( "Rabbot is giving up." );
    rabbit.retry();
} );
```
as you suggested.
You must ensure your subscribers are not exclusively bound using:
`startSubscription( 'your_queue_name', true); `  change to `startSubscription( 'your_queue_name'); `
or they will not continue to get messages after a failure and re-connection.

@arobson 
In addition,  I tried many ways to use either close() or shutdown(), without using retry(),  to then cleanly rebuild and was not able.  Async calls to close() or shutdown() just hung and synchronous calls followed by process.nextTick(  some_cool_reinitialize_fn )  just ran into problems with internal fsm state.  Let me know if you are gonna continue working on support for recovery and I can put some more time into this.    Thx

**Comment by TinOo512** [comment]
@arobson Hi, I have the same issue here. When I try to call `rabbit.retry();` in the `unreachable` callback the topology is rebuild without creating the exchanges back. So when I try to publish any messages again I get this error : 
```
Potentially unhandled rejection [31] Error: Publish failed - no exchange default-ex on connection default is defined
    at .<anonymous> (/home/kontest/workspace/.../node_modules/rabbot/src/index.js:313:25)
    at tryCatchReject (/home/kontest/workspace/.../node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/kontest/workspace/.../node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/home/kontest/workspace/.../node_modules/when/lib/makePromise.js:592:4)
    at ContinuationTask.run (/home/kontest/workspace/.../node_modules/when/lib/makePromise.js:702:24)
    at Scheduler._drain (/home/kontest/workspace/.../node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/kontest/workspace/.../node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

To reproduce it, you should just stop the message broker `rabbitmq-server` for a few seconds and start it back.

With @johnraber fork which adds @Nopik fix, everything is working well.

What do you think of the fix ? Any plan to release it ?
Or maybe an other solution might be to refactor `index.js` to let us instantiate the `Broker` again ? I'll be glad to work on this If you think it's the best way to resolve this.

**Comment by arobson** [comment]
@TinOo512 @Nopik - I've managed to fix some issues related to reconnection / clean-up / shut-down as of 1.0.8 that I believe may have caused this. Would you try this out and re-open this issue if you're still having the same problem?

**Comment by TinOo512** [comment]
@arobson After some test in local it seems fixed :) Huge thx ! I'll deploy that in production and re-open if the issue occurred again.

**Comment by kestutisbalt** [comment]
Hi @arobson

I have an issue with reconstruction.

If topology is constructed this way:
```
rabbot.configure({
    connection: {
        uri: 'amqp://localhost',
    }
});

rabbot.addExchange('testing', 'topic', { durable: true });

rabbot.on('unreachable', () => rabbot.retry());

```
And RabbitMQ broker is restarted then every subsequent call:

```
rabbot.publish('testing', {
    routingKey: 'testing.event.created',
    contentType: 'application/json',
    body: {
        msg: 'Testing msg',
    },
});
```

Fails with error:

```
Error: Publish failed - no exchange testing on connection default is defined
```

Is this an intended behavior? Since defining topology in `.configure()` does not suffer from this issue.

**Comment by ZitRos** [comment]
I'm occasionally getting the `Publish failed - no exchange _______ on connection default is defined` for our workers as well...
